// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: route_guide.proto

package com.example.grpc.route_guide;

public interface FeatureOrBuilder extends
    // @@protoc_insertion_point(interface_extends:Feature)
    com.google.protobuf.MessageOrBuilder {

  /**
   * <code>string name = 1;</code>
   */
  String getName();
  /**
   * <code>string name = 1;</code>
   */
  com.google.protobuf.ByteString
      getNameBytes();

  /**
   * <code>.Point location = 2;</code>
   */
  boolean hasLocation();
  /**
   * <code>.Point location = 2;</code>
   */
  com.example.grpc.route_guide.Point getLocation();
  /**
   * <code>.Point location = 2;</code>
   */
  com.example.grpc.route_guide.PointOrBuilder getLocationOrBuilder();
}
