/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class Printf3 */

#ifndef _Included_Printf3
#define _Included_Printf3
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     Printf3
 * Method:    fprint
 * Signature: (Ljava/io/PrintWriter;Ljava/lang/String;D)V
 */
JNIEXPORT void JNICALL Java_Printf3_fprint
  (JNIEnv *, jclass, jobject, jstring, jdouble);

/*
 * Class:     Printf3
 * Method:    getProperty
 * Signature: (Ljava/lang/String;)Ljava/lang/String;
 */
JNIEXPORT jstring JNICALL Java_Printf3_getProperty
  (JNIEnv *, jclass, jstring);

/*
 * Class:     Printf3
 * Method:    getFileOutputStream
 * Signature: (Ljava/lang/String;)Ljava/io/FileOutputStream;
 */
JNIEXPORT jobject JNICALL Java_Printf3_getFileOutputStream
  (JNIEnv *, jclass, jstring);

/*
 * Class:     Printf3
 * Method:    multiScaleFactor
 * Signature: ([DD)[D
 */
JNIEXPORT jdoubleArray JNICALL Java_Printf3_multiScaleFactor
  (JNIEnv *, jclass, jdoubleArray, jdouble);

#ifdef __cplusplus
}
#endif
#endif
